//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.FileUpload FileUpload1;
		
		protected System.Web.UI.WebControls.TextBox name;
		
		protected System.Web.UI.WebControls.TextBox address;
		
		protected System.Web.UI.WebControls.TextBox county;
		
		protected System.Web.UI.WebControls.TextBox country;
		
		protected System.Web.UI.WebControls.TextBox dob;
		
		protected System.Web.UI.WebControls.TextBox number;
		
		protected System.Web.UI.WebControls.Button btnsave;
		
		protected System.Web.UI.WebControls.Label lblmessage;
	}
}
